### ISSUE TITLE
Template parse errors: Can't bind to 'restaurant' since it isn't a known property of 'app-restaurant-detail'.

### ISSUE THREAD

**Issue by Matt-Keister** [Matt-Keister/Restaurants#1]
```
Error: Template parse errors:
Can't bind to 'restaurant' since it isn't a known property of 'app-restaurant-detail'.
1. If 'app-restaurant-detail' is an Angular component and it has 'restaurant' input, then verify that it is part of this module.
2. If 'app-restaurant-detail' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
	</li>
</ul>
<app-restaurant-detail [ERROR ->][restaurant]="selectedRestaurant"></app-restaurant-detail>"): ng:///DynamicTestModule/RestaurantsComponent.html@7:23
'app-restaurant-detail' is not a known element:
1. If 'app-restaurant-detail' is an Angular component, then verify that it is part of this module.
2. If 'app-restaurant-detail' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
	</li>
</ul>
[ERROR ->]<app-restaurant-detail [restaurant]="selectedRestaurant"></app-restaurant-detail>"): ng:///DynamicTestModule/RestaurantsComponent.html@7:0
    at syntaxError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:485:22)
    at TemplateParser.webpackJsonp../node_modules/@angular/compiler/esm5/compiler.js.TemplateParser.parse (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:24668:1)
    at JitCompiler.webpackJsonp../node_modules/@angular/compiler/esm5/compiler.js.JitCompiler._parseTemplate (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:34621:1)
    at JitCompiler.webpackJsonp../node_modules/@angular/compiler/esm5/compiler.js.JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:34596:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:34497:48
    at Set.forEach (<anonymous>)
    at JitCompiler.webpackJsonp../node_modules/@angular/compiler/esm5/compiler.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:34497:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:34385:1
    at Object.then (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:474:33)
    at JitCompiler.webpackJsonp../node_modules/@angular/compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:34383:1)
```

**Comment by Matt-Keister** [comment]
This issue was only present during testing and the app worked as expected.  I had forgotten to import and declare a new component when configuring my testing modules.
